const rules = {
    'alt-text': 2,
    'anchor-ambiguous-text': 2,
    'anchor-has-content': 2,
    'anchor-is-valid': 2,
    'aria-activedescendant-has-tabindex': 2,
    'aria-props': 2,
    'aria-proptypes': 2,
    'aria-role': 2,
    'aria-unsupported-elements': 2,
    'autocomplete-valid': 2,
    'click-events-have-key-events': 2,
    'control-has-associated-label': 2,
    'heading-has-content': 2,
    'html-has-lang': 2,
    'iframe-has-title': 2,
    'img-redundant-alt': 2,
    'interactive-supports-focus': 2,
    'label-has-associated-control': 2,
    'lang': 2,
    'media-has-caption': 2,
    'mouse-events-have-key-events': 2,
    'no-access-key': 2,
    'no-aria-hidden-on-focusable': 2,
    'no-autofocus': 2,
    'no-distracting-elements': 2,
    'no-interactive-element-to-noninteractive-role': 2,
    'no-noninteractive-element-interactions': 2,
    'no-noninteractive-element-to-interactive-role': 2,
    'no-noninteractive-tabindex': 2,
    'no-redundant-roles': 2,
    'no-static-element-interactions': 2,
    'prefer-tag-over-role': 2,
    'role-has-required-aria-props': 2,
    'role-supports-aria-props': 2,
    'scope': 2,
    'tabindex-no-positive': 2,
};

export default Object.fromEntries(Object.entries(rules).map(e => [`a11y/${e[0]}`, e[1]]));
