const rules = {
    'accessor-pairs': 2,
    'array-callback-return': 2,
    'arrow-body-style': 2,
    'block-scoped-var': 2,
    'camelcase': [2, { properties: 'never' }],
    'capitalized-comments': 2,
    'class-methods-use-this': 2,
    'complexity': [2, { max: 30 }],
    'consistent-return': 2,
    'consistent-this': 2,
    'constructor-super': 2,
    'curly': [2, 'multi-line'],
    'default-case': 2,
    'default-case-last': 2,
    'default-param-last': 2,
    'dot-notation': 2,
    'eqeqeq': 2,
    'for-direction': 2,
    'func-name-matching': 2,
    'func-names': [2, 'never', { generators: 'always' }],
    'func-style': [2, 'declaration', { allowArrowFunctions: true }],
    'getter-return': 2,
    'grouped-accessor-pairs': 2,
    'guard-for-in': 2,
    'id-denylist': 2,
    'id-length': [2, { min: 1 }],
    'id-match': 2,
    'init-declarations': 2,
    'logical-assignment-operators': 2,
    'max-classes-per-file': 2,
    'max-depth': 2,
    'max-lines': 2,
    'max-lines-per-function': [2, { max: 100, skipBlankLines: true, skipComments: true }],
    'max-nested-callbacks': 2,
    'max-params': [2, { max: 5 }],
    'max-statements': [2, { max: 20 }],
    'new-cap': [2, { properties: false }],
    'no-alert': 2,
    'no-array-constructor': 2,
    'no-async-promise-executor': 2,
    'no-await-in-loop': 2,
    'no-bitwise': [2, { allow: ['&', '|', '^'] }],
    'no-caller': 2,
    'no-case-declarations': 2,
    'no-class-assign': 2,
    'no-compare-neg-zero': 2,
    'no-cond-assign': 2,
    'no-console': 2,
    'no-const-assign': 2,
    'no-constant-binary-expression': 2,
    'no-constant-condition': 2,
    'no-constructor-return': 2,
    'no-continue': 2,
    'no-control-regex': 2,
    'no-debugger': 2,
    'no-delete-var': 2,
    'no-div-regex': 2,
    'no-dupe-args': 2,
    'no-dupe-class-members': 2,
    'no-dupe-else-if': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-duplicate-imports': 2,
    'no-else-return': 2,
    'no-empty': [2, { allowEmptyCatch: true }],
    'no-empty-character-class': 2,
    'no-empty-function': 2,
    'no-empty-pattern': 2,
    'no-empty-static-block': 2,
    'no-eq-null': 2,
    'no-eval': 2,
    'no-ex-assign': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-label': 2,
    'no-fallthrough': 2,
    'no-func-assign': 2,
    'no-global-assign': 2,
    'no-implicit-coercion': 2,
    'no-implicit-globals': 2,
    'no-implied-eval': 2,
    'no-import-assign': 2,
    'no-inline-comments': 2,
    'no-inner-declarations': 2,
    'no-invalid-regexp': 2,
    'no-invalid-this': 2,
    'no-irregular-whitespace': 2,
    'no-iterator': 2,
    'no-label-var': 2,
    'no-labels': 2,
    'no-lone-blocks': 2,
    'no-lonely-if': 2,
    'no-loop-func': 2,
    'no-loss-of-precision': 2,
    'no-magic-numbers': 0,
    'no-misleading-character-class': 2,
    'no-multi-assign': 2,
    'no-multi-str': 2,
    'no-negated-condition': 2,
    'no-nested-ternary': 2,
    'no-new': 2,
    'no-new-func': 2,
    'no-new-native-nonconstructor': 2,
    'no-new-wrappers': 2,
    'no-nonoctal-decimal-escape': 2,
    'no-obj-calls': 2,
    'no-object-constructor': 2,
    'no-octal': 2,
    'no-octal-escape': 2,
    'no-param-reassign': 2,
    'no-plusplus': [2, { allowForLoopAfterthoughts: true }],
    'no-promise-executor-return': 2,
    'no-proto': 2,
    'no-prototype-builtins': 2,
    'no-redeclare': 2,
    'no-regex-spaces': 2,
    'no-restricted-exports': 2,
    'no-restricted-globals': 2,
    'no-restricted-imports': 2,
    'no-restricted-properties': 2,
    'no-restricted-syntax': 2,
    'no-return-assign': 2,
    'no-script-url': 2,
    'no-self-assign': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-setter-return': 2,
    'no-shadow': 2,
    'no-shadow-restricted-names': 2,
    'no-sparse-arrays': 2,
    'no-template-curly-in-string': 2,
    'no-ternary': 0,
    'no-this-before-super': 2,
    'no-throw-literal': 2,
    'no-undef': 2,
    'no-undef-init': 2,
    'no-undefined': 2,
    'no-underscore-dangle': 2,
    'no-unexpected-multiline': 2,
    'no-unmodified-loop-condition': 2,
    'no-unneeded-ternary': 2,
    'no-unreachable': 2,
    'no-unreachable-loop': 2,
    'no-unsafe-finally': 2,
    'no-unsafe-negation': 2,
    'no-unsafe-optional-chaining': 2,
    'no-unused-expressions': 2,
    'no-unused-labels': 2,
    'no-unused-private-class-members': 2,
    'no-unused-vars': 2,
    'no-use-before-define': [2, { functions: false }],
    'no-useless-assignment': 2,
    'no-useless-backreference': 2,
    'no-useless-call': 2,
    'no-useless-catch': 2,
    'no-useless-computed-key': 2,
    'no-useless-concat': 2,
    'no-useless-constructor': 2,
    'no-useless-escape': 2,
    'no-useless-rename': 2,
    'no-useless-return': 2,
    'no-var': 2,
    'no-void': [2, { allowAsStatement: true }],
    'no-warning-comments': 2,
    'no-with': 2,
    'object-shorthand': 2,
    'one-var': [2, 'never'],
    'operator-assignment': 2,
    'prefer-arrow-callback': 2,
    'prefer-const': 2,
    'prefer-destructuring': [2, { array: false }],
    'prefer-exponentiation-operator': 2,
    'prefer-named-capture-group': 2,
    'prefer-numeric-literals': 2,
    'prefer-object-has-own': 2,
    'prefer-object-spread': 2,
    'prefer-promise-reject-errors': 2,
    'prefer-regex-literals': 2,
    'prefer-rest-params': 2,
    'prefer-spread': 2,
    'prefer-template': 2,
    'radix': 2,
    'require-atomic-updates': 2,
    'require-await': 2,
    'require-unicode-regexp': 2,
    'require-yield': 2,
    'sort-imports': [2, { allowSeparatedGroups: true }],
    'sort-keys': 2,
    'sort-vars': 2,
    'strict': 2,
    'symbol-description': 2,
    'unicode-bom': 2,
    'use-isnan': 2,
    'valid-typeof': 2,
    'vars-on-top': 2,
    'yoda': [2, 'never', { exceptRange: true }],
};

export default rules;
