const prettier = {
    arrowParens: 'avoid',
    bracketSameLine: false,
    bracketSpacing: true,
    embeddedLanguageFormatting: 'auto',
    endOfLine: 'lf',
    filepath: '',
    htmlWhitespaceSensitivity: 'css',
    insertPragma: false,
    jsxSingleQuote: false,
    parser: 'typescript',
    printWidth: 100,
    proseWrap: 'preserve',
    quoteProps: 'as-needed',
    rangeEnd: 100000,
    rangeStart: 0,
    requirePragma: false,
    semi: true,
    singleAttributePerLine: false,
    singleQuote: true,
    tabWidth: 4,
    trailingComma: 'all',
    useTabs: false,
    vueIndentScriptAndStyle: true,
};

export default prettier;
